// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: complex_data.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplexDataService_GetData_FullMethodName = "/proto.ComplexDataService/GetData"
)

// ComplexDataServiceClient is the client API for ComplexDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComplexDataServiceClient interface {
	GetData(ctx context.Context, in *ComplexDataRequest, opts ...grpc.CallOption) (*ComplexDataResponse, error)
}

type complexDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplexDataServiceClient(cc grpc.ClientConnInterface) ComplexDataServiceClient {
	return &complexDataServiceClient{cc}
}

func (c *complexDataServiceClient) GetData(ctx context.Context, in *ComplexDataRequest, opts ...grpc.CallOption) (*ComplexDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComplexDataResponse)
	err := c.cc.Invoke(ctx, ComplexDataService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplexDataServiceServer is the server API for ComplexDataService service.
// All implementations must embed UnimplementedComplexDataServiceServer
// for forward compatibility.
type ComplexDataServiceServer interface {
	GetData(context.Context, *ComplexDataRequest) (*ComplexDataResponse, error)
	mustEmbedUnimplementedComplexDataServiceServer()
}

// UnimplementedComplexDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplexDataServiceServer struct{}

func (UnimplementedComplexDataServiceServer) GetData(context.Context, *ComplexDataRequest) (*ComplexDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedComplexDataServiceServer) mustEmbedUnimplementedComplexDataServiceServer() {}
func (UnimplementedComplexDataServiceServer) testEmbeddedByValue()                            {}

// UnsafeComplexDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplexDataServiceServer will
// result in compilation errors.
type UnsafeComplexDataServiceServer interface {
	mustEmbedUnimplementedComplexDataServiceServer()
}

func RegisterComplexDataServiceServer(s grpc.ServiceRegistrar, srv ComplexDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedComplexDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplexDataService_ServiceDesc, srv)
}

func _ComplexDataService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComplexDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplexDataServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplexDataService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplexDataServiceServer).GetData(ctx, req.(*ComplexDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplexDataService_ServiceDesc is the grpc.ServiceDesc for ComplexDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplexDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ComplexDataService",
	HandlerType: (*ComplexDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _ComplexDataService_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "complex_data.proto",
}
